version: '3.5'
services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    environment:
      - RAILS_ENV=development
    entrypoint: ["sh", "./entrypoint.sh"]
    ports:
      - 3000:3000
